//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SILMARILLION_FINAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SILMARILLION_FINAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string LOG {
            get {
                return ResourceManager.GetString("LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Była blisko spokrewniona z Hurin Thalionem, władcą Dor-lóminu. Była córką Indora. Zamieszkiwała Dor-lómin.
        ///
        ///          Została zmuszona do ślubu wbrew jej woli przez Easterlinga Broddę, po tym jak został on władcą Hithlumu. W tajemnicy pomagała żonie Hurina, Morwenie, po bitwie Nirnaeth Arnoediad, i za tą pomoc była bita przez swego męża.
        ///
        ///          Kiedy Turin powrócił do Dor-lóminu, zaproponowano mu gościnę w jej domu. Dowiedział się od Aeriny, że jego matka i siostra wyruszyły do Doriathu.
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_aerin {
            get {
                return ResourceManager.GetString("s_aerin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_aerin1 {
            get {
                object obj = ResourceManager.GetObject("s_aerin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerina - kobieta z rodu Hadora, krewna Morweny. Mieszkała w Dor-Lominie, gdzie po Nirnaeth Arnoediad wyszła za mąż za Easterlinga imieniem Brodda. Pomogła Morwenie i Turinowi, po uwięzieniu Hurina. Gdy Turin powrócił do domu szukać siostry i matki wstąpił do niej szukając informacji, zabił wtedy będących tam Easterlingów, między innymi Broddę..
        /// </summary>
        internal static string s_aerina {
            get {
                return ResourceManager.GetString("s_aerina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Był to jeden z wielkich władców ludzi z przeszłości Śródziemia, wywodzący się spośród Dunedainów z Numenoru. Tak jak ojciec i brat, był sojusznikiem elfów, razem z nimi walczył w wojnie z Sauronem, podczas której zginął.
        ///
        ///           Anarion pojawia się w Silmarillionie. Wspominają o nim także bohaterowie Władcy Pierścieni. Pewne informacje na jego temat znajdują się w Dodatkach do trzeciego tomu powieści oraz w Niedokończonych opowieściach.
        ///
        ///          Anarion, choć był postacią wybitną, w pewnym s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_anarion {
            get {
                return ResourceManager.GetString("s_anarion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_anarion1 {
            get {
                object obj = ResourceManager.GetObject("s_anarion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Barahir - człowiek z Rodu Beora, syn Bregora, mąż Emeldir i ojciec Berena. Miał czwórkę rodzeństwa: Bregolasa, Bregil, Hirwen i Gilwen.
        ///
        ///          Mieszkał w Ladrosie. W czasie bitwy wspomógł on Felagunda i uratował mu życie. Ten w zamian dał mu swój pierścień i obiecał pomoc w potrzebie jemu i jego rodowi. W taki właśnie sposób Barahir otrzymał Pierścień Barahira. Później został zabity przez orków razem z towarzyszami w Taur-nu-Fuin, z powodu zdrady Gorlima. Jego syn odbił pierścień i pokonał prz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_barahir {
            get {
                return ResourceManager.GetString("s_barahir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_barahir1 {
            get {
                object obj = ResourceManager.GetObject("s_barahir1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Mieszkał w królestwie Doriathu, dowodził strażnikami broniącymi jego granic. Słynął z waleczności i umiejętności tropicielskich. Najbardziej znany był jednak jako mistrz posługiwania się łukiem Belthrondingiem i strzałą Dailir. On i Mablung byli jedynymi elfami z Doriathu walczącymi w Nirnaeth Arnoediad. Beleg pomógł również Haladinom w walce z orkami w Brethilu.
        ///
        ///          Był nauczycielem, przyjacielem i towarzyszem broni Turina Turambara. Gdy Turin został wygnany z Doriathu, Beleg, na polecenie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_beleg {
            get {
                return ResourceManager.GetString("s_beleg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_beleg1 {
            get {
                object obj = ResourceManager.GetObject("s_beleg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           ByĹ‚ Edainem, czĹ‚owiekiem z rodu Beora, synem Barahira. SpotkaĹ‚ w lesie Neldoreth w Doriath Luthien, cĂłrkÄ™ krĂłla Thingola. ZakochaĹ‚ siÄ™ w niej i poprosiĹ‚ krĂłla o jej rÄ™kÄ™. Thingol zaĹĽÄ…daĹ‚ w zamian Silmarila z korony Morgotha.
        ///
        ///          Beren i Luthien z pomocÄ… Huana i Finroda Felagunda zdobyli Silmaril, lecz Carcharoth, wilk Angbandu, odgryzĹ‚ Berenowi w czasie ucieczki z twierdzy Morgotha dĹ‚oĹ„ razem z odzyskanym klejnotem.
        ///
        ///          Jako jedyny ze Ĺ›miertelnikĂłw Beren wrĂłciĹ‚ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_beren {
            get {
                return ResourceManager.GetString("s_beren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_beren1 {
            get {
                object obj = ResourceManager.GetObject("s_beren1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Był zamożnym hobbitem, synem Bunga Bagginsa i Belladony Took. Mieszkał w Bag End w Hobbitonie.
        ///
        ///          W 2941 wraz z Gandalfem, Thorinem Dębową Tarczą oraz dwunastoma innymi krasnoludami wyruszył na wyprawę odebrania Samotnej Góry smokowi Smaugowi. Przygoda ta zaprowadziła Bilba i jego towarzyszy do Rivendell, Mrocznej Puszczy i ostatecznie do Ereboru, gdzie po zajęciu góry przez Thorina miała miejsce Bitwa Pięciu Armii.
        ///
        ///          W 2941 wraz z Gandalfem, Thorinem Dębową Tarczą oraz dwunastoma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_bilbo {
            get {
                return ResourceManager.GetString("s_bilbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_bilbo1 {
            get {
                object obj = ResourceManager.GetObject("s_bilbo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Brandir (Brandir Kulawy) - wódz ludu Halethy w latach 496 do 501 PE. Zakochał się w Nienor, którą uzdrowił. Skłamał ludowi Halethy i został za to zabity przez Turina..
        /// </summary>
        internal static string s_brandir {
            get {
                return ResourceManager.GetString("s_brandir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_brandir1 {
            get {
                object obj = ResourceManager.GetObject("s_brandir1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Urodzony w Amanie w czasie trwania Lat Drzew. Tak jak wszyscy oni złożył przysięgę mówiącą o ściganiu wszystkich istot posiadających Silmarile. Krótko po przybyciu do Beleriandu poczuł się zlekceważony przez króla Thingola pozwalającemu osiedlić się Noldorom w Hithlumie i wyruszył na wschód. Tam założył królestwo, Dor Caranthir (Thargelion). Zamieszkał tam na brzegu jeziora Helevorn. Wybudował też fortecę na zboczach góry Rerir. Królestwo to wzbogaciło się niezwykle dzięki kontrolowaniu handlu cen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_caranthir {
            get {
                return ResourceManager.GetString("s_caranthir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_caranthir1 {
            get {
                object obj = ResourceManager.GetObject("s_caranthir1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Elf ze szczepu Telerich. Jego prawdziwe imię brzmiało Nowe. Był żeglarzem i szkutnikiem. 
        ///
        ///          Bardzo wysoki, pod koniec Trzeciej Ery miał wygląd starca i jako jedyny Elf w Śródziemiu nosił długą brodę (był więc w trzecim etapie życia). Prawdopodobnie był jednym z elfów przebudzonych nad Cuivienen. 
        ///
        ///          W Pierwszej Erze władał Falas i przez długi czas trzymał się z dala od sporów Noldorów i Sindarów. Po zniszczeniu krainy w następstwie bitwy Nirnaeth Arnoediad przeniósł się wraz z Gil [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_cirdan {
            get {
                return ResourceManager.GetString("s_cirdan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_cirdan1 {
            get {
                object obj = ResourceManager.GetObject("s_cirdan1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Silmarillion - obok Władcy Pierścieni oraz Hobbita jedno z najbardziej znanych dzieł J.R.R. Tolkiena.
        ///
        ///          To od niego Tolkien zaczął tworzyć legendarium, których pisanie zajęło mu całe życie. 
        ///Pierwsze wersje opowieści wchodzących w jego skład powstały w roku 1917 i były rozwijane z przerwami na Hobbita i Władcę Pierścieni, aż do śmierci pisarza w roku 1973. 
        ///
        ///          Książka została ukończona i wydana cztery lata po śmierci autora przez jego syna Christophera. Przed śmiercią autor chciał [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_default {
            get {
                return ResourceManager.GetString("s_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Był wojownikiem i przewodził tym Haladinom z Brethilu, którzy chętnie wyprawiali się przeciw orkom.
        ///
        ///          W 496 roku, na czele znacznego oddziału, zasadził się przy przeprawie przez Teiglin na maszerujących ze zdobytego Nargothrondu żołdaków Morgotha. Haladinowie liczyli na to, iż uda im się odbić jeńców, jednak na samym początku walki orkowie wymordowali więźniów, wśród których była księżniczka Finduilas. Nim zmarła, zdołał wyjawić swoje imię ludziom Dorlasa, którzy pochowali ją pod kurhanem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_dorlas {
            get {
                return ResourceManager.GetString("s_dorlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_dorlas1 {
            get {
                object obj = ResourceManager.GetObject("s_dorlas1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Zwany jest również Żeglarzem, Płomieniem Westernesse, Gwiazdą Zachodu oraz Gil-Estelem.
        ///
        ///          Był synem Tuora i Idril, półelfem, urodzonym przed upadkiem Gondolinu. Jego żoną była Elwinga. Miał synów Elronda i Elrosa.
        ///
        ///          Earendil urodził się w roku 504 Pierwszej Ery w Gondolinie. Jako dziecko osiadł w Arvernien, ośrodku morskim, gdzie Cirdan zaszczepił mu szczególną miłość do morza. Później Earendil stał się władcą Arvenien.
        ///
        ///          Na swym okręcie Vingilot przemierzał wody Belegae [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_earendil {
            get {
                return ResourceManager.GetString("s_earendil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_earendil1 {
            get {
                object obj = ResourceManager.GetObject("s_earendil1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           ByĹ‚ to jeden z wielkich wĹ‚adcĂłw ludzi z przeszĹ‚oĹ›ci ĹšrĂłdziemia, przywĂłdca NumenorejczykĂłw, ktĂłrzy pozostali wierni Valarom i przeĹĽyli zatopienie ojczystej wyspy. Elendil, wraz z synami, zaĹ‚oĹĽyĹ‚ krĂłlestwa Arnor i Gondor. Zwiazany sojuszem z elfami, walczyĹ‚ z Sauronem. Jego odlegĹ‚ym potomkiem byĹ‚ Aragorn, czĹ‚onek DruĹĽyny PierĹ›cienia.
        ///
        ///          ByĹ‚ Dunadanem, urodzonym w Numenorze, synem Amandila, ostatniego ksiÄ™cia Andunië. Podobnie jak wĹ‚adcy Numenoru wywodziĹ‚ siÄ™ od Eare [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_elendil {
            get {
                return ResourceManager.GetString("s_elendil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_elendil1 {
            get {
                object obj = ResourceManager.GetObject("s_elendil1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Elrond (sin. gwiazda-kopuĹ‚a) - postaÄ‡ ze stworzonej przez J.R.R. Tolkiena mitologii ĹšrĂłdziemia. ByĹ‚ panem Rivendell, potomkiem wĹ‚adcĂłw ĹĽyjÄ…cych w Pierwszej Erze, ktĂłry pozostaĹ‚ w ĹšrĂłdziemiu do koĹ„ca Trzeciej Ery.
        ///
        ///          Elrond byĹ‚ synem Earendila (Noldora, prawnuka Fingolfina) i Elwingi (prawnuczki Thingola), urodzonym w Beleriandzie w Pierwszej Erze, co oznacza, ĹĽe podczas wydarzeĹ„ opisanych we WĹ‚adcy PierĹ›cieni miaĹ‚ ponad 6000 lat. Bratem Elronda byĹ‚ Elros, pierwszy krĂł [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_elrond {
            get {
                return ResourceManager.GetString("s_elrond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_elrond1 {
            get {
                object obj = ResourceManager.GetObject("s_elrond1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Urodzony przed początkiem Pierwszej Ery, zamordowany w 345 roku Pierwszej Ery.
        ///
        ///          Początkowo był członkiem rodu królewskiego w Doriacie. Kiedy Meliana opasała Doriath swoją Obręczą, Eol wyprowadził się z lasu Region do Nan Elmoth, na wschód od Doriathu.
        ///
        ///          Eol był zręcznym rzemieślnikiem i mistrzem w kuciu mieczy. Wynalazł galvorn. Z niego zrobił sobie zbroję, którą nosił, i dwa miecze: Anglachel i Anguriel. Anglachela podarował Thingolowi jako zapłatę za to, że może mieszkać w Nan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_eol {
            get {
                return ResourceManager.GetString("s_eol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_eol1 {
            get {
                object obj = ResourceManager.GetObject("s_eol1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Eru Iluvatar - postać ze stworzonej przez J.R.R. Tolkiena mitologii śródziemia. Wszechmocny Bóg, stwórca Ainurów, Ea, Ardy i jej mieszkańców. Opiekę nad Ardą przekazał Ainurom (z Valarami na czele).
        ///
        ///          Jego imiona pochodzą z quenyi, Eru znaczy Jedyny, zaś Iluvatar - Ojciec Wszechrzeczy. W tekstach Tolkiena używa się ich obu w zestawieniu lub pojedynczo.
        ///
        ///          Eru został przedstawiony w Silmarillionie. W Ainulindale wprowadza tematy do muzyki. Następnie w Akallabeth, po tym, jak Manwe  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_eru {
            get {
                return ResourceManager.GetString("s_eru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_eru1 {
            get {
                object obj = ResourceManager.GetObject("s_eru1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Była córką Orodretha z Nargothrondu, kochała Gwindora,który nazywał ją Faelivrin.
        ///
        ///          Gdy Turin przybył do królestwa jej ojca wraz z Gwindorem, Finduilas zakochała się w Turinie, jednak nie żywił on do niej takiej miłości jakiej pragnęła.
        ///
        ///          Po zniszczeniu Nargothrondu została zabita przez uciekających po złupieniu jej królestwa orków.
        ///
        ///          Turin po wielkich trudach nie zdołał jednak ocalić Finduilas. Została ona przyszpilona włócznią do drzewa, podczas próby uratowania niewol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_finduilas {
            get {
                return ResourceManager.GetString("s_finduilas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_finduilas1 {
            get {
                object obj = ResourceManager.GetObject("s_finduilas1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Fingon - elf, syn Fingolfina i Anaire, ojciec Gil-galada. Został Najwyższym Królem Noldorów po śmierci swego ojca. Władał Dor-lóminem, a po śmierci Fingolfina - całym Hithlumem. Był jednym z dowódców w bitwie Nirnaeth Arnoediad, w czasie której został zabity przez Gothmoga..
        /// </summary>
        internal static string s_fingon {
            get {
                return ResourceManager.GetString("s_fingon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_fingon1 {
            get {
                object obj = ResourceManager.GetObject("s_fingon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Finrod - król Noldorów, najstarszy syn Finarfina, władca Nargothrondu.
        ///
        ///          Zbudował cytadelę Minas Tirith na Sirionie oraz Nargothrond na Narogu. Był przyjacielem krasnoludów od których otrzymał naszyjnik Nauglamir. Około 310 roku Pierwszej Ery przypadkowo spotkał pierwszych ludzi w Ossiriandzie. Niedługo potem ich przywódca Beor wstąpił do Finroda na służbę. W roku 455 razem z Berenem i dziesięcioma elfami z Nargothrondu wyruszył po Silmaril, dotrzymując przysięgi złożonej Barahirowi. Rząd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_finrod {
            get {
                return ResourceManager.GetString("s_finrod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_finrod1 {
            get {
                object obj = ResourceManager.GetObject("s_finrod1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Był jedynym synem Droga i Primuli z Brandybucków. Młodość spędził w Bucklandzie, po śmierci rodziców w 2980 został adoptowany przez Bilba Bagginsa i sprowadził się do Bag End. W Shire przyjaźnił się z Peregrinem Tukiem, Meriadokiem Brandybuckiem, Folko Boffinem i Fredegarem Bolgerem.
        ///
        ///          Po wyruszeniu Bilba w ostatnią wyprawę (3001 rok Trzeciej Ery) mieszkał samotnie do 3018 roku. Sprzedał wtedy Bag End Lobelii i Lotho Sackville-Bagginsom i wyruszył do Rivendell. Po drodze w Bree spotkał Ar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_frodo {
            get {
                return ResourceManager.GetString("s_frodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_frodo1 {
            get {
                object obj = ResourceManager.GetObject("s_frodo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Galadriela - kobieta z rasy elfow, z krolewskiego rodu plemienia Noldorow. Corka Finarfina i Earweny, siostra Finroda Felagunda, Aegnora i Angroda.
        ///
        ///          UwaĹĽana za jednÄ… z najwiÄ™kszych Eldarow, wymienianÄ… obok Luthien, moĹĽe ustÄ™pujÄ…cÄ… jedynie Feanorowi, chociaĹĽ mÄ…drzejszÄ… od niego. Jej rola i znaczenie wzrastaĹ‚y wraz z tworzeniem mitologii Ĺšrodziemia, trudne jest wiÄ™c pogodzenie wszystkich wÄ…tkow i szczegoĹ‚ow z jej ĹĽycia.
        ///
        ///          Jej pragnienie wĹ‚adzy doprowadziĹ‚o do te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_galadriela {
            get {
                return ResourceManager.GetString("s_galadriela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_galadriela1 {
            get {
                object obj = ResourceManager.GetObject("s_galadriela1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Gandalf jest czarodziejem, jednym z Istarich, ktĂłrzy przybyli do ĹšrĂłdziemia w Trzeciej Erze.
        ///
        ///          Gandalf byĹ‚ jednym z MajarĂłw o imieniu OlĂłrin. UchodziĹ‚ za najmÄ…drzejszego wĹ›rĂłd MajarĂłw mieszkajÄ…cych w Amanie, przebywaĹ‚ czÄ™sto w LĂłrien, wiele wÄ™drowaĹ‚ i nierzadko odwiedzaĹ‚ dom Nienny - od niej to nauczyĹ‚ siÄ™ cierpliwoĹ›ci, spokoju oraz umiĹ‚owania dla wszystkich istot zamieszkujÄ…cych ArdÄ™. OlĂłrin bardzo kochaĹ‚ Quendich, takĹĽe tych przebywajÄ…cych w ĹšrĂłdziemiu. Prz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_gandalf {
            get {
                return ResourceManager.GetString("s_gandalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_gandalf1 {
            get {
                object obj = ResourceManager.GetObject("s_gandalf1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Pierwszy ze smoków (Uruloki), nazywany ich Ojcem, jeden z najpotężniejszych smoków Ardy. W 265 r. Pierwszej Ery został wypuszczony z Angbandu, jednak nie osiągał wtedy swoich największych rozmiarów, a Noldorowie zmusili go do ucieczki. W Dagor Bragollach i w Nirnaeth Arnoediad Glaurung, już w pełni sił, przewodził straży przedniej Morgotha i siał olbrzymie spustoszenie na polu bitwy. W Nirnaeth Arnoediad został ciężko raniony przez Azaghala, władcę Belegostu, którego zabił, lecz musiał uciec z pol [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_glaurung {
            get {
                return ResourceManager.GetString("s_glaurung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_glaurung1 {
            get {
                object obj = ResourceManager.GetObject("s_glaurung1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Glorfindel - elf, jeden z wodzów w Gondolinu, a także uczestnik obrad Białej Rady. Prawdopodobnie także jedyny elf, który po śmierci powrócił znów do Śródziemia. Jego śmierć miała miejsce podczas walki z Barlogiem w Gondolinie. Możliwe, że to Valarowie pozwolili mu wrócić do Śródziemia. Elf osiadł w Rivendell, w domu Elronda. Był jednym z niewielu, których bał się Czarnoksiężnik z Angmaru. Brał udział w Bitwie pod Fornostem i to właśnie wtedy przepowiedział Czarnoksiężnikowi z Angmaru że nie zgini [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_glorfindel {
            get {
                return ResourceManager.GetString("s_glorfindel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_glorfindel1 {
            get {
                object obj = ResourceManager.GetObject("s_glorfindel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Gothmog - wódz Balrogów, dowódca sił Angbandu. Był odpowiedzialny za znaczne cierpienia, jakich doznała Arda w Pierwszej Erze. Został stworzony przez Eru Iluvatara, przed początkami Ardy. Szybko przyłączył się do Melkora i stał się jednym z jego najpotężniejszych sług, potęgą ustępując miejsca tylko Sauronowi.
        ///
        ///          Gothmog uniknął śmierci w Wielkiej Bitwie Potęg i przyłączył ponownie do Melkora po jego powrocie z Amanu. Wraz z innymi Balrogami uratował go przed Ungoliantą.
        ///
        ///          Był dow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_gothmog {
            get {
                return ResourceManager.GetString("s_gothmog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_gothmog1 {
            get {
                object obj = ResourceManager.GetObject("s_gothmog1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Huor - czĹ‚owiek z Rodu Hadora, syn Galdora z Dor-lĂłminu, mÄ…ĹĽ Riany, ojciec Tuora.UrodziĹ‚ siÄ™ w Dor-lĂłminie, jako syn Galdora z Rodu Hadora i Harethy, cĂłrki Halmira, wĹ‚adcy HaladinĂłw. WychowywaĹ‚ siÄ™, razem z bratem Hurinem w lesie Brethil, pod opiekÄ… ich wuja, Haldira.
        ///
        ///          Brali udziaĹ‚ w walkach z orkami, mimo iĹĽ Huor miaĹ‚ dopiero 13 lat. Podczas pewnej bitwy zostali odciÄ™ci od towarzyszy i byli Ĺ›cigani przez orkĂłw, aĹĽ do brodĂłw Brithiach. ZginÄ™liby, gdyby nie moc Ulma  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_huor {
            get {
                return ResourceManager.GetString("s_huor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_huor1 {
            get {
                object obj = ResourceManager.GetObject("s_huor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Jest jednym z wielkich wojownikĂłw ludzi z okresu Pierwszej Ery, wiernym sojusznikiem elfĂłw. Nawet po przegranej bitwie i wziÄ™ciu do niewoli, nie ulega Morgothowi, wĹ‚adcy siĹ‚ zĹ‚a, choÄ‡ sprowadza to na jego rodzinÄ™ klÄ…twÄ™. Przez to losy samego bohatera, jak i wszystkich jego bliskich, naznaczone sÄ… cierpieniem i nieszczÄ™Ĺ›ciami.
        ///
        ///          Hurin pojawia siÄ™ w Silmarillionie, Dzieciach Hurina i NiedokoĹ„czonych opowieĹ›ciach. Wspomina siÄ™ o nim rĂłwnieĹĽ we WĹ‚adcy PierĹ›cieni.
        ///
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_hurin {
            get {
                return ResourceManager.GetString("s_hurin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_hurin1 {
            get {
                object obj = ResourceManager.GetObject("s_hurin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Idril Celebrindal - elfka ze szczepu Noldorów, córka Turgona i Elenwe, wnuczka Fingolfina, żona Tuora, matka Earendila Żeglarza. Była bardzo piękna i mądra. Miała złote włosy.
        ///
        ///          Idril urodziła się w rodzinie królewskiej elfów w Valinorze, między 1300 a 1500 Ery Drzew. Była w pięciu ósmych Vanyarem (po matce i babce ojca). Prawie straciła życie pośród lodów w czasie podróży do Śródziemia, jednak ojciec uratował ją.
        ///
        ///          Osiedlili się w Gondolinie, gdzie jej ojciec został władcą. Zako [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_idril {
            get {
                return ResourceManager.GetString("s_idril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_idril1 {
            get {
                object obj = ResourceManager.GetObject("s_idril1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Indis - druga ĹĽona Finwego, krĂłla NoldorĂłw w Amanie. Po tym jak pierwszÄ… jego ĹĽonÄ™, Míriel opuĹ›ciĹ‚y siĹ‚y podczas narodzin Feanora i musiaĹ‚a udaÄ‡ siÄ™ do ogrodow Lorien, FinwepojÄ…Ĺ‚ za ĹĽonÄ™ siostrÄ™ swojego przyjaciela, Ingwego. Mieli dwĂłch synĂłw - Fingolfina i Finarfina oraz dwie cĂłrki: Findis i Irime. Indis wychowywaĹ‚a rownieĹĽ swojego pasierba, jednak Feanor nigdy nie pokochaĹ‚ jej ani swojego rodzeĹ„stwa z czego wyniknÄ™Ĺ‚o pĂłĹşniej wiele zĹ‚ego. Po tym, jak Melkor zabiĹ‚ Fin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_indis {
            get {
                return ResourceManager.GetString("s_indis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_indis1 {
            get {
                object obj = ResourceManager.GetObject("s_indis1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Urwena ( qya. ur - ogień, wen - dziewczynka) (466 - 469 PE) - córka Hurina Thaliona i Morweny, siostra Turina Turambara i Nienor. Przez wiele osób była nazywana Lalaith co znaczy śmiech. Zmarła w wieku 3 lat, gdy Dor-lómin ogarnęła zaraza z Angbandu..
        /// </summary>
        internal static string s_lalaith {
            get {
                return ResourceManager.GetString("s_lalaith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_lalaith1 {
            get {
                object obj = ResourceManager.GetObject("s_lalaith1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Luthien (sin. czarodziejka), zwana także Tinuviel (sin. słowik) - postać ze stworzonej przez J.R.R. Tolkiena mitologii śródziemia. Inspiracją dla tej postaci była żona Tolkiena Edith, a na nagrobku pisarza i jego żony obok nazwisk widnieją również ich wieczne imiona: Beren i Luthien.
        ///
        ///          Luthien była córką króla Thingola z Doriath i Meliany. Była najpiękniejszą istotą, jaka kiedykolwiek chodziła po Ardzie, ponieważ łączyła w sobie najlepsze cechy Quendich i Majarów. O jej historii opowiada  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_luthien {
            get {
                return ResourceManager.GetString("s_luthien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_luthien1 {
            get {
                object obj = ResourceManager.GetObject("s_luthien1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           UrodziĹ‚ siÄ™ w Amanie w czasie trwania Lat Drzew i jako jedyny syn Feanora przeĹĽyĹ‚ PierwszÄ… ErÄ™ (jego pĂłĹşniejsze losy nie sÄ… znane). Jego imiÄ™ w quenyi brzmiaĹ‚o Canafinwe, co oznacza Finwe o mocnym (piÄ™knym) gĹ‚osie, a imiÄ™ nadanÄ™ mu przez matkÄ™ to Macalaure – KujÄ…cy ZĹ‚oto. NawiÄ…zywaĹ‚o ono do jego umiejÄ™tnoĹ›ci gry na harfie.
        ///
        ///          ByĹ‚ drugim synem Feanora i Nerdaneli, ktĂłry odziedziczyĹ‚ po matce jej delikatnÄ… naturÄ™. ZostaĹ‚ sĹ‚ynnym minstrelem. Maglor widziaĹ‚ Ĺ›mier [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_maglor {
            get {
                return ResourceManager.GetString("s_maglor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_maglor1 {
            get {
                object obj = ResourceManager.GetObject("s_maglor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Manwe - jeden z Valarów, najpotężniejszy z nich, nieśmiertelny, Aratar, król Ardy.
        ///
        ///          Manwe był Ainurem stworzonym z myśli Iluvatara. Był mężem Vardy. Początkowo ustępował miejsca pod względem potęgi tylko swemu bratu Melkorowi. Kiedy ten próbował zmienić Pieśń Ainurów Manwe pozostał jak najbardziej wierny Eru i nie podążył przeciw niemu.
        ///
        ///          Kiedy Muzyka dobiegła końca część Ainurów udała się do stworzonego świata - Ardy. Będąc tam zobaczyli jednak, że świat ten jest tylko marzenie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_manwe {
            get {
                return ResourceManager.GetString("s_manwe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_manwe1 {
            get {
                object obj = ResourceManager.GetObject("s_manwe1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Jedna z Majarów, żona Thingola, matka Luthien i królowa Doriathu.
        ///
        ///          Została stworzona przez Eru Iluvatara, przed początkami Ardy.
        ///
        ///          Mieszkała w ogrodach Irma i Este, Lórien. Mieszkańcy Amanu powiadali, że nie było istoty piękniejszej, mądrzejszej i o piękniejszym głosie niż Meliana. Gdy śpiewała, Majarowie i Valarowie porzucali swe zajęcia, a ptaki przerywały szczebiot, by jej wysłuchać. Była służącą Yavanny.
        ///
        ///          Po przebudzeniu się elfów, Meliana opuściła Aman, i zamieszk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_meliana {
            get {
                return ResourceManager.GetString("s_meliana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_meliana1 {
            get {
                object obj = ResourceManager.GetObject("s_meliana1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Mim żył w Amon Rudh, pośrodku Beleriandu wraz ze swoimi dwoma synami Ibun i Khimem. Kiedy Turin Turambar przebywał w tej okolicy z bandą banitów, krasnolud wraz z synami próbowali się przemknąć, jednak zostali dostrzeżeni przez banitów i Mim został pojamny, a Khima śmiertelnie postrzelił z łuku jeden z banitów - Andróg. W zamian za puszczenie wolno krasnolud oddał swoją kryjówkę zwaną od tego momentu Bar-en-Danwedh, co znaczy Dom Okupu. Gdy do Amon Rudh przybył Beleg Cuthalion, Mim był wściekły, g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_mim {
            get {
                return ResourceManager.GetString("s_mim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_mim1 {
            get {
                object obj = ResourceManager.GetObject("s_mim1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Miriel (qya. Klejnot-kobieta) - zwana również Miriel Serinde pierwsza żona Finwego oraz matka Feanora. Zmarła w ogrodach Lórien w wyniku wyczerpania po ciężkim porodzie Feanora..
        /// </summary>
        internal static string s_miriel {
            get {
                return ResourceManager.GetString("s_miriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_miriel1 {
            get {
                object obj = ResourceManager.GetObject("s_miriel1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Początkowo miał na imię Melkor. Był najpotężniejszym Ainurem, ponadto miał udział w wiedzy i władzy każdego z pozostałych Ainurów. Często zapuszczał się samotnie w Pustkę (wydawało mu się, że Iluvatar nie ma co do niej żadnych planów; palony żądzą stwarzania Bytów własnego pomysłu niecierpliwie pragnął wypełnić ją po swojemu). Zazdrościł Manwemu zwierzchnictwa nad Valarami, stał się pyszny i przewrotny. Skomponował, a następnie wprowadził własne motywy do Ainulindale. Później razem z innymi Ainura [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_morgoth {
            get {
                return ResourceManager.GetString("s_morgoth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Morwena - postaÄ‡ ze stworzonej przez J.R.R. Tolkiena mitologii ĹšrĂłdziemia. Jej losy opisane zostaĹ‚y w ksiÄ…ĹĽkach Silmarillion, NiedokoĹ„czone opowieĹ›ci oraz Dzieci Hurina.ByĹ‚a kobietÄ… z ludu EdainĂłw.
        ///          PochodziĹ‚a z rodu Beora i byĹ‚a cĂłrkÄ… Baragunda, ĹĽonÄ… Hurina, matkÄ… trojga dzieci: Turina, Urweny oraz Nienor.Od urodzenia mieszkaĹ‚a w Ladros, ale po Bitwie NagĹ‚ego PĹ‚omienia kobiety i dzieci Rodu, wĹ›rĂłd ktĂłrych znajdowaĹ‚a siÄ™ Morwena oraz jej kuzynka Ríana, wyruszyĹ‚y [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_morwena {
            get {
                return ResourceManager.GetString("s_morwena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_morwena1 {
            get {
                object obj = ResourceManager.GetObject("s_morwena1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Nienor (sin. Lament, także Niniel, łza-kobieta) - postać ze stworzonej przez J.R.R. Tolkiena mitologii Śródziemia. 
        ///
        ///          Była ludzką kobietą, córką Hurina i Morweny oraz siostrą i żoną Turina Turambara.Jako dziecko zbiegła wraz z matką z Dor-lóminu do Doriathu, gdzie została wychowana na dworze króla Thingola. Jako nastoletnia dziewczyna wyruszyła razem z grupą elfów, na poszukiwania brata do Nargothrondu, gdzie zastała jedynie smoka Glaurunga, który rzucił na nią czar, wskutek czego stracił [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_nienor {
            get {
                return ResourceManager.GetString("s_nienor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_nienor1 {
            get {
                object obj = ResourceManager.GetObject("s_nienor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Był szesnastym namiestnikiem rządzącym Gondorem. Urząd objął w 2655 roku i sprawował go do końca swego życia, przez 30 lat. Zmarł w 2685 roku.
        /// </summary>
        internal static string s_orodreth {
            get {
                return ResourceManager.GetString("s_orodreth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_orodreth1 {
            get {
                object obj = ResourceManager.GetObject("s_orodreth1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Radagast Bury, pierwotnie Aiwendil - majar, jeden z pięciu Istarich, którzy przybyli do Śródziemia na początku Trzeciej Ery, by wspomagać Wolne Ludy w walce z Sauronem.
        ///
        ///          Radagast był jednym z Majarów stworzonych z myśli Iluvatara. Po stworzeniu świata zstąpił z wieloma innymi Ainurami na Ardę, gdzie przybrał imię Aiwendil. Mieszkał w Amanie i był sługą Yavanny.
        ///
        ///          Około 1000 roku Trzeciej Ery został na prośbę Yavanny jednym z Istarich. Miał chronić w Śródziemiu przyrodę przed złe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_radagast {
            get {
                return ResourceManager.GetString("s_radagast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_radagast1 {
            get {
                object obj = ResourceManager.GetObject("s_radagast1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Najpotężniejszy z Istarich wysłanych do Śródziemia. Zajmował wyższą pozycję, niż pozostali, został więc przywódcą wyprawy i otrzymał szaty koloru białego. Został na tę misję wskazany przez Aulego, któremu służył i był podobny w zainteresowaniach. Stąd brał się tytuł Sarumana - &quot;Mistrz Rzemiosł&quot;. Miał także zdolność przekonywania umysłów słabszych od swojego.
        ///
        ///          Pierwotnie miało zostać wysłanych trzech Majarów, drugim został Alatar. Kiedy Manwe zaproponował, by jako trzeci dołączył Olórin,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_saruman {
            get {
                return ResourceManager.GetString("s_saruman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_saruman1 {
            get {
                object obj = ResourceManager.GetObject("s_saruman1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Sauron (qya. Ohydny).
        ///
        ///          Sauron był władcą Mordoru, złym duchem, który przybierał różne postaci cielesne. Został stworzony przez Iluvatara przed początkiem czasu tak jak wszyscy Ainurowie i zstąpił na Ardę razem z wieloma spośród nich.
        ///
        ///          Sauron był pierwotnie jednym z Majarów w służbie Aulego, lecz wcześnie został znieprawiony przez Melkora. Ten uczynił go swoją prawą ręką. Był w tych czasach zarządcą dwóch ważnych twierdz Melkora: najpierw Angbandu (gdy istniało jeszcze Utumno),  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_sauron {
            get {
                return ResourceManager.GetString("s_sauron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_sauron1 {
            get {
                object obj = ResourceManager.GetObject("s_sauron1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Elu Thingol lub Elwe - elf naleĹĽÄ…cy do Telerich, ĹĽyjÄ…cych w Pierwszej Erze. MÄ…ĹĽ Meliany, ojciec Luthien i krĂłl Doriathu. Jak wszyscy ojcowie elfĂłw, obudziĹ‚ siÄ™ nad Cuiviénen. Jego braÄ‡mi byli Olwe i Elmo.
        ///
        ///          Elu Thingol byĹ‚ jednym z przywĂłdcĂłw swego ludu, ktĂłrzy ujrzeli Dwa Drzewa Valinoru. PowrĂłciwszy do ĹšrĂłdziemia miaĹ‚ przekonaÄ‡ swoich pobratymcĂłw do zamieszkania w Valinorze, jednak staĹ‚o siÄ™, ĹĽe zakochaĹ‚ siÄ™ w Melianie z MajarĂłw. Razem zamieszkali w Beleriandz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_thingol {
            get {
                return ResourceManager.GetString("s_thingol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_thingol1 {
            get {
                object obj = ResourceManager.GetObject("s_thingol1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           ByĹ‚ Adanem, bohaterem Trzeciego rodu EdainĂłw, jedynym synem Huora i Riany, kuzynem Turina, Lalaith oraz Niënor. PoczÄ™ty zostaĹ‚ tuĹĽ przed Ĺ›mierciÄ… Huora w bitwie Nirnaeth Arnoediad. ZostaĹ‚ przygarniÄ™ty przez Annaela, Sindara z Mithrimu, gdyĹĽ Riana zmarĹ‚a wkrĂłtce po jego urodzeniu z powodu ĹĽalu po Ĺ›mierci Huora. Tuor spÄ™dziĹ‚ dzieciĹ„stwo w jaskiniach Androth, lecz kiedy miaĹ‚ 16 lat, Sindarowie zostali schwytani podczas prĂłby ucieczki do przystani Sirionu. Tuor zostaĹ‚ niewolnikiem  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_tuor {
            get {
                return ResourceManager.GetString("s_tuor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_tuor1 {
            get {
                object obj = ResourceManager.GetObject("s_tuor1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Elf ze szczepu Noldorów, drugi syn Fingolfina i Anaire, król Gondolinu.
        ///W Valinorze Turgon przyjaźnił się z synami Finarfina, wraz z nimi wyruszył też na wygnanie do Śródziemia. Jego żona Elenwe zginęła podczas podróży, do nowych ziem dotarł więc tylko z córką Idril. Zamieszkał w krainie Nevrastu, gdzie wybudował Vinyamar. Wkrótce potem od Ulma otrzymał instrukcje, dotyczące budowy ukrytego królestwa. Umieścił je w górach Echoriath i zniknął w nim na ponad 500 lat.
        ///
        ///          Pomimo ukrycia wojsk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_turgon {
            get {
                return ResourceManager.GetString("s_turgon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_turgon1 {
            get {
                object obj = ResourceManager.GetObject("s_turgon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           Turin Turambar (ur. 463 roku Pierwszej Ery w Dor-lĂłminie, zm. 499 roku Pierwszej Ery w Cabed-en-Aras) - postaÄ‡ ze stworzonej przez J.R.R. Tolkiena mitologii ĹšrĂłdziemia, wĹ‚adca Dor-lĂłminu, syn Hurina Thaliona i Morweny, brat Urweny Lalaith oraz Nienor Niniel, ktĂłrej byĹ‚ takĹĽe mÄ™ĹĽem.
        ///
        ///          Znany pod licznymi imionami Neithan, Gorthol, Agarwaen syn Úmartha, Thurin, Adanedhel, Mormegil i Turambar, ktĂłre czÄ™sto przybieraĹ‚ po to, by uciec przed klÄ…twÄ… Morgotha.
        ///
        ///          UrodziĹ‚ s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string s_turin {
            get {
                return ResourceManager.GetString("s_turin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_turin1 {
            get {
                object obj = ResourceManager.GetObject("s_turin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap s_unknown {
            get {
                object obj = ResourceManager.GetObject("s_unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
